import { 
  BsStars,
  BsCloudFill,
  BsFillCreditCardFill,
} from 'react-icons/bs'
import {
  MdOutlineSecurity,
  MdVisibility,
} from 'react-icons/md'
import { 
  IoCopy 
} from 'react-icons/io5'
import { IconType } from 'react-icons/lib';

export interface IFeature {
  name: string;
  description: string;
  icon: IconType
};

export const features: IFeature[] = [
  {
    name: 'Easily Start',
    description: 'In just a few steps deploy and automate your safe-scaling infrastructure making your services responsive 24/7.',
    icon: BsStars,
  },
  {
    name: 'All in the Cloud',
    description: 'Set up your AWS account and SleakOps will generate your Infra in a correct and safe manner.',
    icon: BsCloudFill,
  },
  {
    name: 'Security and Access Control',
    description: 'SleakOps relies on the best practices, experience, and knowledge of all our expert engineers.',
    icon: MdOutlineSecurity,
  },
  {
    name: 'Observability',
    description: 'You can monitor your infra to review status, resources, and services at any moment. ',
    icon: MdVisibility,
  },
  {
    name: 'Manage Environment',
    description: 'With the management of the environments on your hands, your releases are going to be safe and your developers can deploy and test with all the freedom they need.',
    icon: IoCopy,
  },
  {
    name: 'Expense Visibility',
    description: 'Check in real-time all the expenses generated by each resource in your AWS account.',
    icon: BsFillCreditCardFill,
  },
]
